### ISSUE TITLE
where I can find Indian famous person name list

### ISSUE THREAD

**Issue by Micy1919** [hellohaptik/chatbot_ner#21]
Hi, I am working about NER of Indian person name, where I can find a Indian person name list, thanks

**Comment by chiragjn** [comment]
You can look  at 
Indian-Female-Names.csv
https://gist.github.com/mbejda/9b93c7545c9dd93060bd
Indian-Male-Names.csv
https://gist.github.com/mbejda/7f86ca901fe41bc14a63

**Comment by Micy1919** [comment]
thank you very much, I find it a long time
