### ISSUE TITLE
Need support for Gujarati NER from text document

### ISSUE THREAD

**Issue by dikshan817** [hellohaptik/chatbot_ner#238]
Hi, 
You have done good work in Chatbot ner. I am doing research on the same. I need python support to implement HMM (Hidden Markov Model) for NER. 
Waiting for your reply.

**Comment by chiragjn** [comment]
Hi @dikshan817 Can you please elaborate your use case ? What entities are you looking for ? At this point we only support deterministic NER by adding data variants in Gujarati

**Comment by dikshan817** [comment]
Thank you for your response.
I am doing NER in the Gujarati Language.  For that, I need support to identify 3 class entities (person name, location, and organization). I need support how to apply HMM for the same.

**Comment by chiragjn** [comment]
Hey @dikshan817, for now, we don't have a very clean API to training CRF models but we do support it. Can you go through the following guide and see if it helps? https://github.com/hellohaptik/chatbot_ner/tree/develop/models/crf_v2

**Comment by chiragjn** [comment]
Closing this for now. Feel free to open again if any help is needed

**Comment by dikshan817** [comment]
I am looking for person name, date, location and organisation name.
