### ISSUE TITLE
while runing the chatbot_ner API in  python shell we are getting this error

### ISSUE THREAD

**Issue by prasannaonchip** [hellohaptik/chatbot_ner#265]
File "ner_v2/detectors/temporal/date/date_detection.py", line 22, in <module>
    from ner_v2.detectors.temporal.utils import get_timezone
  File "ner_v2/detectors/temporal/utils.py", line 4, in <module>
    import pandas as pd
  File "/home/swathi/.local/lib/python2.7/site-packages/pandas/__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']

thanks in advance

**Comment by swathionchip** [comment]
Hi All,

First uninstall numpy versions all by giving the below command till numpy not available.
Ex: **_pip uninstall numpy_** or **_pip3  uninstall numpy_**

later install numpy based on the Ubuntu version.

Regards,
Swathi.

**Comment by prasannaonchip** [comment]
ok solved
