### ISSUE TITLE
helloaptik/chatbot_ner works with Python 2.7.x but not with Python 3

### ISSUE THREAD

**Issue by prasannaonchip** [hellohaptik/chatbot_ner#273]
helloaptik chatbot_ner is working for python version 2.x with and without docker.
we have one doubt is it(hellohaptik chatbotbot_ner) supports for python version 3.x

_Originally posted by @prasannaonchip in https://github.com/hellohaptik/chatbot_ner/issues/268#issuecomment-507547037_

**Comment by chiragjn** [comment]
Unfortunately, it does not support Python 3, but we do plan to finish porting it by the end of this year
