### ISSUE TITLE
New entity adding named as distance

### ISSUE THREAD

**Issue by prasannaonchip** [hellohaptik/chatbot_ner#281]
Hi 
we are trying to add new entity by using the your tool, 
For adding New entity we followed the procedure what you are given in the document 
 named as **chatbot_ner/docs/adding_entities.md**
here
**from datastore import DataStore
csv_file = 'data/entity_data/distance.csv'
db = DataStore()
db.populate(csv_file_paths=[csv_file,])** 
by using this code we added the new entites 

the data which is present in the distance.csv is given below

**values,variants
distance,distance|distances
kilometer,kilometer|kilometers|km|kms
miles,miles|miles
nearest,nearest
nearby,nearby
shortest,shortest|shortest
quickest,quickest|quick** 

it is working fine but we want 

Need a coffee place within 4 miles with the quickest route. 
in this sentence i want to predict the value and unit .
Here in this sentence value is 4 and unit is miles and also quickest is distance entity.
i want to predict the output in this form  for that how i can add units regarding distance, and also how can access it .
 

please reply fast 
thanks in advance.

**Comment by chiragjn** [comment]
I'll add more details when I get some time, but we support <number><unit> detection with the new number detector
But in short, you can add your units here with the unit_type "distance": https://github.com/hellohaptik/chatbot_ner/blob/develop/ner_v2/detectors/numeral/number/en/data/units.csv
and then when using number detector you can pass "distance" as `unit_type`


Following is an example with `unit_type` as "currency", which already exists in the data file

```
message=u"i want more than Rupees 20k and 10 pendrive"
entity_name='number'
structured_value=None
fallback_value=None
bot_message=None
min_number_digits=1
max_number_digits=6
source_language='en' # here language will be ISO 639-1 code
unit_type='currency' # this restrict the number detector to detect particular number type only.

from ner_v2.detector.number.number.number_detection import NumberDetector
detector = NumberDetector(entity_name=entity_name, language=source_language, 
                          unit_type=unit_type)  
detector.set_min_max_digits(min_digit=min_number_digits, max_digit=max_number_digits) 
output = detector.detect(message=message,structured_value=structured_value,
                         fallback_value=fallback_value, bot_message=bot_message)
print(output)
```

which gives

```
{
  "data": [
    {
      "detection": "message",
      "original_text": "rupees 20k",
      "entity_value": {
        "unit": "rupees",
        "value": "20000"
      },
      "language": "en"
    }
  ]
}
```
