### ISSUE TITLE
Running chatbot _ner without docker 

### ISSUE THREAD

**Issue by vaisakhcherrylabs** [hellohaptik/chatbot_ner#425]
Is it possible to run the project without docker for development purpose.?

**Comment by chiragjn** [comment]
Hey @vaisakhcherrylabs, it is certainly possible and in the past we used to run it with a virtualenv setup (https://github.com/hellohaptik/chatbot_ner/blob/e69c2a6980398753836485efe86bd2b4e2c132c1/docs/install.md). But as you know it will involve installing and setting up everything carefully manually. To avoid all that we switched to Docker

**Comment by vaisakhcherrylabs** [comment]
Thank you
