### ISSUE TITLE
Could it be trained in other languages, such as in Spanish?

### ISSUE THREAD

**Issue by imanoluria** [hellohaptik/chatbot_ner#6]
Hello! Firstly thanks for your great job and all the support with the codes. I was wondering if it would be possible o train the model in other languages, such as in Spanish, and how could it be possible. 

Thanks again!

**Comment by apurvnagvenkar** [comment]
Hi,
Currently, chatbot_ner is heuristic based that uses a dictionary based format to identify necessary entity values. For training/identification of entities for other languages, we might have to modify a code a bit so it supports characters other than ASCII.
You can have a look at the documentation on [How to add entities?](https://github.com/hellohaptik/chatbot_ner/blob/master/docs/adding_entities.md) in case if you want to to try it out by adding new entities.

Thanks and Regards.
